### ISSUE TITLE
Preparation for 2019

### ISSUE THREAD

**Issue by andrewda** [andrewda/frc-livescore#20]
- [ ] Parse match summary screens (https://github.com/andrewda/frc-livescore/issues/2)
- [x] Add 2019 templates when released
- [ ] Getting https://github.com/andrewda/frc-livescore/issues/4 working would be good
- [ ] Add multi-language support (already started in #17)

**Comment by fangeugene** [comment]
I've got 2019 template parsing working. Don't want to commit to a public repo for now though.

Also fixed 1xx->3xx issue (e.g. https://www.thebluealliance.com/match/2018new_qm1)

Multi-language support #17 might be easier now that Tesseract 4.0.0 has been released.

**Comment by andrewda** [comment]
Sounds great, thanks @fangeugene!
